# DATA CLEANING

In [52]:
import pandas as pd

In [53]:
file_path = r'C:\Users\HP\projects\EdTech Retention Analytics\data\raw\mooc_data.csv'
df = pd.read_csv(file_path)

In [54]:
print("Dataset Loaded Successfully")
df.head()

Dataset Loaded Successfully

,course_id,userid_DI,registered,viewed,explored,certified,final_cc_cname_DI,LoE_DI,YoB,gender,grade,start_time_DI,last_event_DI,nevents,ndays_act,nplay_video,nchapters,nforum_posts,roles,incomplete_flag
0,HarvardX/CB22x/2013_Spring,MHxPC130442623,1,0,0,0,United States,NaN,NaN,NaN,0,12/19/12,11/17/13,NaN,9.0,NaN,NaN,0,NaN,1.0
1,HarvardX/CB22x/2013_Spring,MHxPC130275857,1,0,0,0,United States,NaN,NaN,NaN,0,2/8/13,11/17/13,NaN,16.0,NaN,NaN,0,NaN,1.0
2,HarvardX/CB22x/2013_Spring,MHxPC130539455,1,1,0,0,France,NaN,NaN,NaN,0,1/1/13,5/14/13,42.0,6.0,NaN,3.0,0,NaN,NaN
3,HarvardX/CB22x/2013_Spring,MHxPC130088379,1,1,0,0,United States,NaN,NaN,NaN,0,2/18/13,3/17/13,70.0,3.0,NaN,3.0,0,NaN,NaN
4,HarvardX/CB22x/2013_Spring,MHxPC130024894,1,1,0,0,United States,NaN,NaN,NaN,0.07,1/24/13,8/3/13,175.0,9.0,NaN,7.0,0,NaN,NaN

In [55]:
# Remove duplicate rows
df = df.drop_duplicates()

In [56]:
# Handle missing values
print(df.isnull().sum())

course_id                 0
userid_DI                 0
registered                0
viewed                    0
explored                  0
certified                 0
final_cc_cname_DI         0
LoE_DI                44119
YoB                   38504
gender                32961
grade                 25890
start_time_DI             0
last_event_DI        152231
nevents              159278
ndays_act            142510
nplay_video          304946
nchapters            144465
nforum_posts              0
roles                338223
incomplete_flag      260838
dtype: int64

In [57]:
# Rename columns
df = df.rename(columns={
    'userid_DI': 'student_id',
    'ndays_act': 'login',
    'nplay_video': 'video_watched',
    'grade': 'assignment_submitted',
    'nforum_posts': 'forum_activity',
    'nevents': 'engagement'
})

# Create dropout column
df['dropout'] = 1 - df['certified']

In [58]:
df.head()

,course_id,student_id,registered,viewed,explored,certified,final_cc_cname_DI,LoE_DI,YoB,gender,...,start_time_DI,last_event_DI,engagement,login,video_watched,nchapters,forum_activity,roles,incomplete_flag,dropout
0,HarvardX/CB22x/2013_Spring,MHxPC130442623,1,0,0,0,United States,NaN,NaN,NaN,...,12/19/12,11/17/13,NaN,9.0,NaN,NaN,0,NaN,1.0,1
1,HarvardX/CB22x/2013_Spring,MHxPC130275857,1,0,0,0,United States,NaN,NaN,NaN,...,2/8/13,11/17/13,NaN,16.0,NaN,NaN,0,NaN,1.0,1
2,HarvardX/CB22x/2013_Spring,MHxPC130539455,1,1,0,0,France,NaN,NaN,NaN,...,1/1/13,5/14/13,42.0,6.0,NaN,3.0,0,NaN,NaN,1
3,HarvardX/CB22x/2013_Spring,MHxPC130088379,1,1,0,0,United States,NaN,NaN,NaN,...,2/18/13,3/17/13,70.0,3.0,NaN,3.0,0,NaN,NaN,1
4,HarvardX/CB22x/2013_Spring,MHxPC130024894,1,1,0,0,United States,NaN,NaN,NaN,...,1/24/13,8/3/13,175.0,9.0,NaN,7.0,0,NaN,NaN,1

In [59]:
print(df.shape)

(338223, 21)

In [60]:
# Fill missing numerical values with 0
numeric_columns = ['login', 'video_watched', 'assignment_submitted']
for col in numeric_columns:
    df[col] = df[col].fillna(0)

In [61]:
# Convert activity date into datetime
df['last_event_DI'] = pd.to_datetime(df['last_event_DI'])

C:\Users\HP\AppData\Local\Temp\ipykernel_35488\3458324789.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['last_event_DI'] = pd.to_datetime(df['last_event_DI'])

In [62]:
# Create week column
df['week'] = df['last_event_DI'].dt.isocalendar().week

In [63]:
# Save cleaned data
output_path = r'C:\Users\HP\projects\EdTech Retention Analytics\data\processed\cleaned_data.csv'
df.to_csv(output_path, index=False)

In [51]:
print("Cleaned Data Saved")

Cleaned Data Saved